---
title: "Countability"
---

During a first year analysis tutorial I tasked the students with the following exercise:

> Let $(a_n)_{n \in \mathbb{N}}$ be a sequence. We are given that the subsequence of terms $(a_{2k})_{k \in \mathbb{N}}$ with even index and the subsequence $(a_{2k-1})_{k \in \mathbb{N}}$ of terms with odd index converge to the same limit $L$. We wish to prove that full sequence $(a_n)_{n \in \mathbb{N}}$ converges to $L$.

This is an easy exercise. After fixing an arbitrary $\epsilon > 0$ we find two 'cut off' indices: the first for which all even terms beyond the cut off are within distance $\epsilon$ of $L$; and the second for which all odd terms beyond the cut off are within distance $\epsilon$ of $L$. To finish we choose the full sequence cut off to be the maximum of the even and odd cut offs.

It's important to note that the proof relies on the fact that the union of the index sequences $(2k)$ and $(2k - 1)$ contains all of $\mathbb{N}$. Moreover, we can easily extend the proof to obtain the following result:

> Let $(a_n)_{n \in \mathbb{N}}$ be a sequence. Suppose we are given that finite collection of subsequences which all converge to the same limit $L$, and whose union of index sequences contains all of $\mathbb{N}_{>k}$ for some finite $k$. We can conclude that $(a_n)_{n \in \mathbb{N}}$ converges to $L$.

A student then asked if an analogous result holds for a countably infinite collection of subsequences. The method of proof used for the finite collection of subsequences breaks down for a countable collection as the maximum of a countable set (of cut offs in this case) is not necessarily finite. This should provoke us to look for a counterexample for which the cut off indices for each subsequence may exist arbitrarily far along the full sequence.

We obtain a counterexample by considering the sequence $a_n:=1$ if $n$ is prime, $a_n := 0$ if $n$ is composite. The countable collection of subsequences we choose is $(a_{pk})_{k \in \mathbb{N}}$ for each and every prime number $p$. It is clear that the union of the corresponding index sequences is $\mathbb{N}_{>1}$. Furthermore, every subsequence in the collection is exactly equal to $(1,0,0,0,...)$ and thus converges to $0$. The full sequence is not convergent however since it is not Cauchy. In particular, $|a_{p+1} - a_p| = 1$ for all primes $p$ greater than $2$.

------------------------------------------------------------------------

I felt that the first year student's question had a sneaky enough answer to be worth frustrating some of the other applied maths PhD students with. Quite surprisingly, a majority could not quickly discern if the countably infinite case was true or false. Try out this prank on some of your friends who have long since studied first year analysis!
