project:
  type: website
  output-dir: docs

website:
  title: "Bill Nunn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maths.qmd
        text: Maths
      - href: sls.qmd
        text: SLS

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

