project:
  type: website
  output-dir: docs

website:
  title: "Bill Nunn"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: maths.qmd
        text: "Maths"
      - href: sls.qmd
        text: "SLS"
      - href: conference.qmd
        text: "Conference"
        
  sidebar:
  - title: "Tutorials"
    style: "docked"
    background: light
    contents:
      - conference.qmd
      - day-one.qmd
      - day-two.qmd
      - keynote.qmd
      - student.qmd
      
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

