---
title: "Keynote Speakers"
---

**Name:** Richard Morey

**Talk Title:** Failures in forensic meta-analysis and the culture of science reform

**Abstract:** Increased awareness the pernicious effects of publication bias and opportunistic data analysis over the past few decades have led scientists to question the statistical evidence in the published literature. Forensic meta-analysis methods are statistical methods designed to find problematic bodies of work. The ‘p-curve’ (Simonsohn, Nelson, Simmons, 2014; Simonsohn, Simmons, Nelson, 2015) is a suite of tests advertised as the ‘key to the file drawer’, supposedly assessing the ‘evidential value’ of a set of findings while accounting for selective publication. In the ten years since publication, the p-curve has simultaneously become extremely popular yet has never been evaluated from a formal statistical perspective. I evaluate these tests by traditional theoretical statistical criteria and find severe statistical problems: undue sensitivity, inadmissibility, nonmonotonicity, and inconsistency. The fact that such a method has escaped scrutiny for 10 years reveals that the scientific reform movement has problems that mirror the problems science at large, including incentives for novelty, peer review failures, and lack of skepticism.

------------------------------------------------------------------------

**Name:** Sara Jabbari

**Talk Title:** Novel antimicrobial treatments and the importance of the host response.

**Abstract:** The global rise in antimicrobial resistance levels, coupled with the downturn in discovery of new antibiotics, has resulted in an urgent need for novel ways to tackle bacterial infections. Creative targets for such treatments include blocking resistance or virulence mechanisms employed by the bacteria. However, such approaches that do not directly kill the bacteria can rely heavily on an effective immune response. We demonstrate how mathematical modelling can be used to understand the consequences of this and to design effective treatment strategies.

------------------------------------------------------------------------

**Name:** Audrey Repetti

**Talk Title:** Proximal Neural Networks for Computational Imaging

**Abstract:** A common approach to solve inverse imaging problems relies on finding a maximum a posteriori (MAP) estimate of the original unknown image, by solving a minimization problem. In this context, iterative proximal algorithms are widely used, enabling to handle non-smooth functions and linear operators. These methods have the advantage of benefiting from strong theoretical guarantees, ensuring their asymptotic convergence to a solution to the problem of interest which is key for decision-making processes. Recently, these proximal algorithms have been paired with deep learning strategies, to further improve the estimate quality. Two main approaches have been investigated in the literature: Plug-and-play algorithms where some of the operators appearing in proximal algorithms are replaced by neural networks, and unfolded neural networks that are obtained by unrolling a proximal algorithm as for finding a MAP estimate, but over a fixed number of iterations, with learned linear operators and parameters.

In this talk, we will explore these different methodological perspectives in computational imaging, and discuss their advantages and limitations.

------------------------------------------------------------------------

**Name:** Waleed Ali

Talk Title: Outreach In & Out of Higher Education

Abstract: Outreach is an important aspect of higher education to encourage the younger generations to think about and appreciate STEM as a career and understand its importance in every day life. This talk will focus on two aspects of outreach: the first is outreach in the conventional sense, where members of the maths department would engage in public interest activities like science fairs or school visits. This part will focus on the efforts that members of the higher education community (staff, UG and PG students) engage with school students or the public in a much broader perspective. The second is outreach that is focussed internally within the department itself. This part will focus on the concerted efforts by staff and PG students to engage the UG cohorts to appreciate the research undergone by academics. These efforts include *Behind the Research* and *PhD Your Way*.
